# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.interfaces.grpc import auth_pb2 as auth__pb2


class AuthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Register': grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=auth__pb2.RegisterRequest.FromString,
            response_serializer=auth__pb2.RegisterResponse.SerializeToString,
        ),
        'Login': grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=auth__pb2.LoginRequest.FromString,
            response_serializer=auth__pb2.LoginResponse.SerializeToString,
        ),
        'RefreshToken': grpc.unary_unary_rpc_method_handler(
            servicer.RefreshToken,
            request_deserializer=auth__pb2.RefreshTokenRequest.FromString,
            response_serializer=auth__pb2.RefreshTokenResponse.SerializeToString,
        ),
        'ValidateToken': grpc.unary_unary_rpc_method_handler(
            servicer.ValidateToken,
            request_deserializer=auth__pb2.ValidateTokenRequest.FromString,
            response_serializer=auth__pb2.ValidateTokenResponse.SerializeToString,
        ),
        'GetProfile': grpc.unary_unary_rpc_method_handler(
            servicer.GetProfile,
            request_deserializer=auth__pb2.GetProfileRequest.FromString,
            response_serializer=auth__pb2.GetProfileResponse.SerializeToString,
        ),
        'ChangePassword': grpc.unary_unary_rpc_method_handler(
            servicer.ChangePassword,
            request_deserializer=auth__pb2.ChangePasswordRequest.FromString,
            response_serializer=auth__pb2.ChangePasswordResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AuthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            '/auth.v1.AuthService/Register',
            request_serializer=auth__pb2.RegisterRequest.SerializeToString,
            response_deserializer=auth__pb2.RegisterResponse.FromString,
            )
        self.Login = channel.unary_unary(
            '/auth.v1.AuthService/Login',
            request_serializer=auth__pb2.LoginRequest.SerializeToString,
            response_deserializer=auth__pb2.LoginResponse.FromString,
            )
        self.RefreshToken = channel.unary_unary(
            '/auth.v1.AuthService/RefreshToken',
            request_serializer=auth__pb2.RefreshTokenRequest.SerializeToString,
            response_deserializer=auth__pb2.RefreshTokenResponse.FromString,
            )
        self.ValidateToken = channel.unary_unary(
            '/auth.v1.AuthService/ValidateToken',
            request_serializer=auth__pb2.ValidateTokenRequest.SerializeToString,
            response_deserializer=auth__pb2.ValidateTokenResponse.FromString,
            )
        self.GetProfile = channel.unary_unary(
            '/auth.v1.AuthService/GetProfile',
            request_serializer=auth__pb2.GetProfileRequest.SerializeToString,
            response_deserializer=auth__pb2.GetProfileResponse.FromString,
            )
        self.ChangePassword = channel.unary_unary(
            '/auth.v1.AuthService/ChangePassword',
            request_serializer=auth__pb2.ChangePasswordRequest.SerializeToString,
            response_deserializer=auth__pb2.ChangePasswordResponse.FromString,
            )
